### PR TITLE
Update Rust CI

### PR DESCRIPTION
**Pull request by lpil**
This brings the Rust CI up to date with the opensource-template

### CODE REVIEW

**Review by soniasingla — COMMENTED** [review]
@lpil under `pull_request` maybe we can also include the PR types: like `[synchronize, opened, reopened, ready_for_review]` & also, path if needed?

**Comment by lpil** [comment]
Could do, though we'd do that in the template repo and then copy it to all other repos. This PR is bringing this repo to to date with the template.

**Review by soniasingla — CHANGES_REQUESTED** [review]
@lpil i will say to add the things mentioned in the above comment in this repo also along with `opensource-template` :)

**Review by celialewis3 — APPROVED** [review]

**Comment by lpil** [comment]
@soniasingla Let's open an issue to discuss any future changes in the template repo rather than blocking this update bringing this repo up to date with the others.

**Pull request merged**
