### PR TITLE
New badge examples

### PR DESCRIPTION
**Pull request by lpil**
Hello!

### Description of Changes

See the [`README-new.md`](https://github.com/EmbarkStudios/opensource/blob/badges/README-new.md) for a demo of the suggested badge configuration from Ari [here](https://github.com/EmbarkStudios/opensource-template/issues/20#issuecomment-716525672).

I've also a [`README-new-with-cc.md`](https://github.com/EmbarkStudios/opensource/blob/badges/README-new-with-cc.md) which is the same but with an
additional shortened contributor covenant badge.

edit: Here's a version with the CC badge in the Contributing section: [`README-new-with-cc-lowered.md`](https://github.com/EmbarkStudios/opensource/blob/badges/README-new-with-cc-lowered.md)

If we're happy with either of these I shall close this PR and update all the READMEs with the new badges.

### Related Issues

- https://github.com/EmbarkStudios/opensource-template/issues/20

Cheers,
Louis

### CODE REVIEW

**Comment by lpil** [comment]
One moment, I missed the deps badge.

**Comment by Jake-Shadle** [comment]
Looks good to me, I definitely like the shorter README-new one, I've always found the contributor conenant to take up too much space. Though maybe it is ok to have that badge further down in the Contributing section?

**Comment by repi** [comment]
Looks good! And think @Jake-Shadle 's idea could be interesting to explore to have a more clear section under "Contributing" instead of a top badge. Not sure how the badge would look like down there, but could also be a bit bigger picture instead of a small badge.

**Comment by lpil** [comment]
Sure thing, here's a version for that: [`README-new-with-cc-lowered.md`](https://github.com/EmbarkStudios/opensource/blob/badges/README-new-with-cc-lowered.md)

**Comment by arirawr** [comment]
Oh nice, I like that last one. That works well.

**Comment by lpil** [comment]
Alrighty well I'll update the repos to use the last one tomorrow unless anyone has reservations. Cheers

**Comment by repi** [comment]
Can you rename the last one to replace the existing README, and we can merge this in after the approvals.

I will also update `.mergify.toml` in here later today so can be more files to propagate to all the repos while we are at it

**Comment by lpil** [comment]
Can do. Given this repo doesn't have CI, Rust deps, etc what shall I do for the badges that use that information?

Currently it's pointing at physx, shall I keep as is? Alternatively I can comment them out with a commented note saying "If you repository contains Rust code use the badges below"?

**Comment by repi** [comment]
I think can continue to leave it pointing to other crates here, but with a comment in the markdown to update or remove it (if we don't have it already).

It is nice to see it directly in the README here of how it looks like

**Comment by lpil** [comment]
Ready to go

**Review by Jake-Shadle — APPROVED** [review]
Nice! :heart:

**Pull request merged**
